FROM python:3.10-slim-bookworm
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1
COPY requirements.txt .


RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

RUN pip install \
    --extra-index-url https://download.pytorch.org/whl/cpu \
    -r requirements.txt

RUN python -c "import nltk; nltk.download('stopwords')"
COPY app.py .

COPY model ./model

COPY src/ ./src

EXPOSE 8080

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
