stages:
  ingest_data:
    cmd: python -m src.pipeline.training.ingest_data
    deps:
    - src/pipeline/training/ingest_data.py
    - src/components/data_ingestion.py
    params:
    - config/config.yaml:
      - data_ingestion
    outs:
    - data/raw

  validate_data:
    cmd: python -m src.pipeline.training.validate_data
    deps:
    - src/pipeline/training/validate_data.py
    - src/components/data_validation.py
    - data/raw
    params:
    - config/config.yaml:
      - data_validation
    outs:
    - artifact/data_validation

  transform_data:
    cmd: python -m src.pipeline.training.transform_data
    deps:
    - src/pipeline/training/transform_data.py
    - src/components/data_transformation.py
    - src/feature_generation
    - data/raw
    params:
    - config/config.yaml:
      - data_transformation
    outs:
    - data/transformed
    - artifact/data_transformation

  model_trainer:
    cmd: python -m src.pipeline.training.model_trainer
    deps:
    - data/transformed
    - src/components/model_trainer.py
    - src/pipeline/training/model_trainer.py
    - src/tuning
    params:
    - config/config.yaml:
      - model_trainer
    outs:
    - artifact/model_trainer
    - model/

  model_evaluation:
    cmd: python -m src.pipeline.training.model_evalute
    deps:
    - model/
    - src/components/model_evaluation.py
    params:
    - config/config.yaml:
      - model_evaluation
      
    metrics:
      - metrics/metrics.json:
          cache: false

    plots:
      - metrics/confusion_metrics.png:
          cache: false