model_trainer:
  level1:
    lr:
      C: 0.01167490683357983
      penalty: l2
      solver: saga
      max_iter: 938
    xgb:
      n_estimators: 570
      max_depth: 3
      learning_rate: 0.01564287714822495
      subsample: 1.0
      colsample_bytree: 0.8
      min_child_weight: 4
      gamma: 0.22183303723570374
      reg_alpha: 0.35769432566321874
      reg_lambda: 0.9031821384617201
  level2:
    lr:
      C: 0.0025762165316021634
      penalty: l2
      solver: saga
      max_iter: 355
