model_trainer:

  preprocess:
    test_size: 0.2
    random_state: 42
    scale: true

  train:
    folds: 5

  level1:
    lr:
      C: 0.011904536214543474
      penalty: l2
      solver: saga
      max_iter: 600

    xgb:
      n_estimators: 193
      max_depth: 5
      learning_rate: 0.05
      subsample: 0.7
      colsample_bytree: 0.8
      min_child_weight: 3
      gamma: 0.05
      reg_alpha: 0.1
      reg_lambda: 1.0

  level2:
    lr:
      C: 0.011904536214543474
      penalty: l2
      solver: saga
      max_iter: 600
