model_trainer:
  level1:
    lr:
      C: 0.03544780944182657
      penalty: l2
      solver: liblinear
      max_iter: 565
    xgb:
      n_estimators: 544
      max_depth: 4
      learning_rate: 0.02520837582831071
      subsample: 1.0
      colsample_bytree: 0.5
      min_child_weight: 5
      gamma: 0.3155234145038879
      reg_alpha: 0.004812707701911919
      reg_lambda: 1.9301373801214607
  level2:
    lr:
      C: 8.569605034935915
      penalty: l2
      solver: liblinear
      max_iter: 324
