required_columns:
  - prompt_name
  - text
  - label

  
columns_dtype:
  prompt_name: object
  text: object
  label: int64


allowed_values:
  label: [0,1]

target_column_name: label
