# STAGE 1: Builder
FROM python:3.11-slim-bookworm AS builder
WORKDIR /install
COPY requirements\requirements_ui.txt .
# Install to a specific prefix to make copying easier
RUN pip install --no-cache-dir --prefix=/install -r requirements.txt

# STAGE 2: Runner
FROM python:3.11-slim-bookworm
WORKDIR /app

# Copy only the installed site-packages from the builder
COPY --from=builder /install/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /install/bin /usr/local/bin

# Copy only the UI code
COPY ui/ .

# Strip out unnecessary python bytecode
RUN find /usr/local -name "*.pyc" -delete && \
    find /usr/local -name "__pycache__" -delete

    
EXPOSE 8501

ENV BACKEND_URL=http://backend:8080/predict
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]